language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
install:
  - travis_retry pip install tox==2.3.1
script:
  - travis_retry tox
notifications:
  webhooks: https://travis-buddy-service.herokuapp.com
  on_success: never # default: always  
  on_failure: always # default: always
  on_start: never   # default: never
  on_cancel: never # default: always
  on_error: never # default: always
